<h1 class="page-header">Users</h1>

<?php echo $this->paginationControl($this->paginator, "Sliding", "pager") ?>
<table class="table table-condensed">
    <thead>
    <tr>
        <th>ID</th>
        <th>Email</th>
        <th  style="width: 30px;">Options</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->items as $user) : ?>
    <tr>
        <td><?=$user->getId();?></td>
        <td><?=$user->getEmail();?></td>
        <td style="text-align: center">
            <a href="#" class="modal-link" data-resource="_admin_user_delete" data-id="<?=$user->getId();?>"><i class="glyphicon glyphicon-remove"></i></a>
        </td>
    </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php echo $this->paginationControl($this->paginator, "Sliding", "pager") ?>