<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/admin.min.css')) ?>

        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
    <header>
        <nav class="navbar navbar-default" role="navigation">
            <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Admin</a>
            </div>

            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="/">Return</a></li>
                    <li><a href="<?=$this->url('auth', ['action' => 'logout'])?>">Logout</a></li>
                </ul>
            </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <div class="content">
            <div class="col-md-3">
                <ul class="nav nav-pills nav-stacked">
                    <li><a href="<?=$this->url('admin')?>">Home</a></li>
                    <li><a href="<?=$this->url('admin', ['controller' => 'user'])?>">Users</a></li>
                </ul>
            </div>

            <div class="col-md-9">
                <?php // flashmessenger setup
                echo $this->flashMessenger()->renderCurrent('error', array('alert', 'alert-dismissible', 'alert-danger'));
                echo $this->flashMessenger()->renderCurrent('info', array('alert', 'alert-dismissible', 'alert-info'));
                echo $this->flashMessenger()->renderCurrent('default', array('alert', 'alert-dismissible', 'alert-warning'));
                echo $this->flashMessenger()->renderCurrent('success', array('alert', 'alert-dismissible', 'alert-success'));
                $this->flashMessenger()->getPluginFlashMessenger()->clearCurrentMessagesFromContainer();
                echo $this->flashMessenger()->render('error', array('alert', 'alert-dismissible', 'alert-danger'));
                echo $this->flashMessenger()->render('info', array('alert', 'alert-dismissible', 'alert-info'));
                echo $this->flashMessenger()->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
                echo $this->flashMessenger()->render('success', array('alert', 'alert-dismissible', 'alert-success'));
                ?>

                <?php echo $this->content; ?>
            </div>
        </div>
    </div>

    <footer>
        <center>&copy; Kai</center>
    </footer>

    <div id="modal"></div>

    <?php echo $this->inlineScript()
        ->prependFile($this->basePath('js/app.js'))
        ->prependFile($this->basePath('js/jquery.magnific-popup.min.js'))
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery.min.js')) ?>

    </body>
</html>
