<div class="col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3">
    <form action="<?=$this->url('auth', ['action' => 'login'])?>" method="POST" class="form-horizontal">

        <div class="form-group">
            <input type="email" name="user[email]" value="<?=$this->user['email']?>" id="user_email"
                   class="form-control" required placeholder="Email">
        </div>

        <div class="form-group">
            <input type="password" name="user[password]" value="" id="user_password"
                   class="form-control" required placeholder="Password">
        </div>

        <p class="text-center"><small>
            <a href="<?=$this->url('auth', ['action' => 'remember'])?>">Forgot your password?</a>
            </small></p>

        <div class="form-group">
            <button type="submit" class="btn btn-primary col-xs-12">Log In</button>
        </div>
    </form>

    <p class="text-center"><small>
        Don't have an account? <a href="<?=$this->url('auth', ['action' => 'register'])?>">Sign up</a>
        </small></p>
</div>
