<div class="col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3">
    <form action="<?=$this->url('auth', ['action' => 'remember'])?>" method="POST" class="form-horizontal">

        <p><small>
                Enter your Email address that you used to register.
                We'll send you an information to reset your password.
            </small></p>

        <div class="form-group">
            <input type="email" name="user[email]" value="<?=$this->user['email']?>" id="user_email"
                   class="form-control" required placeholder="Email">
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary col-xs-12">Send</button>
        </div>
    </form>
    <p class="text-center"><small>
            Already have an account?
            <a href="<?=$this->url('auth', ['action' => 'login'])?>">Log in</a>
        </small></p>
</div>
